### ISSUE TITLE
Resolve promise

### ISSUE THREAD

**Issue by tkvw** [fluffynuts/synchronous-promise#8]
I think there is an issue with resolving promises.
```
let p = Promise.resolve('a');
SynchronousPromise.resolve(p)===p // = true
```
I think SynchronousPromise should only resolve SynchronousPromises. 
```
function looksLikePromise(thing) {
    return thing &&
        thing.then &&
        typeof (thing.pause) === 'function' &&
        typeof (thing.resume) === 'function' &&
        typeof (thing.then) === 'function' &&
        typeof (thing.catch) === 'function';
}
```

**Comment by fluffynuts** [comment]
It's tricky, because then that means that SynchronousPromise does something that no other promise libraries do: treat other promises as different from itself. If you were to do the following with any other promise implementation (using es6 as an example here):
```
var p1 = SynchronousPromise.resolve("moo");
var p2 = Promise.resolve(p1);
p2.then(result => console.log(result)); // logs "moo"
```
Then you'd see that part of the promise expectation is that all promise implementations are treated equally. I don't want to make an arbitrary (and, quite possibly, unexpected) distinction as a blanket choice.

That being said, I can see that you're using SynchronousPromise as a dependency for another great (and obviously useful) framework, so what if we allow a global configuration for SP, turned off by default, which gives you the behavior that you want? I still don't think it's necessarily the correct thing to do, but I could just not be fully understanding your specific use-case.

If this is something you want, I'd like to know what the expected behavior would be, so we can define it well and run with it. SP is meant to make testing easier, so I don't see the problem in making opt-in behavior which is not technically promise-conformant.

**Comment by tkvw** [comment]
Thanks for your extensive answer 👍  
You're right in what you're saying, but allowing this would break behaviour as well. 
Consider this: 
```
        SynchronousPromise.resolve(new Promise(()=>{}))
            .then(r=> console.log(r));
```
The thenable is called before the asynchronous promise is resolved. I just don't see any real use case allowing an async promise in synchronous promises. (The other way around it does!) 
Or am I missing something?

**Comment by fluffynuts** [comment]
I think you are missing something (: or the example above doesn't fit the issue you're experiencing, in which case, I'm missing something (: 

In your example above, the console.log is never called:
```
SynchronousPromise.resolve(new Promise(() => {})).then(r => console.log("cake")); // never logs
```
Which would be the expected behavior.

Again, I'm open to providing behavior modifications for test harnesses if it suits your needs, but not where it breaks expected functionality. I already have one case where expected functionality is broken (https://github.com/fluffynuts/synchronous-promise/issues/7) and I'm even considering a re-write to fix this (since I haven't figured out a lower-effort solution, yet ): )

**Comment by tkvw** [comment]
So, my apology, I made a horrible test that satisfied my thoughts about that one. You're right. 

The issue I'm experiencing is that I want to resolve a value which could be an async promise. But rather than including the thenable in the promise chain I want it to return. Maybe allowing an `isThenable` would do the job? 
***Note*** this feature request is for something I like to include in yup, but could be something the author disagrees with. I want to do this:

```
cons schema = alternatives().promiseOrType(string())
const p = Promise.resolve('dede');
schema.validateSync(p).should.equal(p);
schema.validate(p).should.become("dede"),
```

**Comment by fluffynuts** [comment]
SP was specifically made to work like a promise but make testing easier. The two goals are not orthogonal (:
As I said before, I'm quite happy to have some specific behavior set by a consuming framework - the conversation is around how. 

So I'd ask two questions: 
1. How would you like to enable this behavior from your side? 
2. Does the original code sample you provided result in the behavior you're looking for? 

I'm also open for a PR, if you have a proposed solution. SP has no lofty goals of being a pure promise implementation to rival any other - it's a testing tool. To this end, it should, whilst maintaining expected promise-like behavior, enable other testing frameworks, if at all possible.

**Comment by tkvw** [comment]
Actually, I don't have a use case for this anymore 👍  I solved my issues using another insight/perspective, which is much better. Thanks for your help on this. 

I created a transform schema type: https://github.com/jquense/yup/compare/master...tkvw:schema-transform

**Comment by fluffynuts** [comment]
Excellent. You're welcome (:
